services:
  nexp-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

  dev-api:
    build:
      context: ./
      dockerfile: ./Dockerfile.api.dev
    ports:
      - "3001:3001"
