services:
  next-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  dev-api:
    build:
      context: ./
      dockerfile: ./Dockerfile.api.dev
    environment:
      - "POSTGRES_URL=postgresql://postgres:mysecretpassword@postgres:5432/mydb?schema=public"
      - "REDIS_URL=redis://redis:6379"
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
