FROM golang:1.22-alpine

WORKDIR /build
COPY go.mod .
RUN go mod download
# TODO: Optimize COPY command so that only necessary files are copied
COPY . .
RUN go build -o ./output/bin
EXPOSE 3001
CMD ["/build/output/bin"]