FROM node:18-alpine

COPY --from=golang:1.22-alpine /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"

WORKDIR /app
COPY package*.json .
RUN npm ci
COPY go.mod .
RUN go mod download
COPY . .
RUN npx prisma generate

EXPOSE 3001
CMD ["go", "run", "api.dev.go"]