const fs = require('fs');

function makeDirIfNotExists(dirPath) {
    if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath);
}

function copyFile(filePath, outputPath) {
    const fileContent = fs.readFileSync(filePath, { encoding: 'utf8' });
    const outputFileContent = `// AUTOGENERATED FILE DO NOT EDIT\n// SOURCE FILE: ${filePath}\n\n${fileContent}`;
    fs.writeFileSync(outputPath, outputFileContent);
}

makeDirIfNotExists('./api');
makeDirIfNotExists('./api/t');

copyFile('./pkg/t.go', './api/t.go');
copyFile('./pkg/t/t.go', './api/t/[id].go');
