const fs = require('fs');

function makeDirIfNotExists(dirPath) {
    if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath);
}

function copyFile(filePath, outputPath) {
    const fileContent = fs.readFileSync(filePath, { encoding: 'utf8' });
    const outputFileContent = `// AUTOGENERATED FILE DO NOT EDIT\n// SOURCE FILE: ${filePath}\n\n${fileContent}`;
    fs.writeFileSync(outputPath, outputFileContent);
}

makeDirIfNotExists('./api');
makeDirIfNotExists('./api/users');

copyFile('./pkg/users.go', './api/users.go');
copyFile('./pkg/users/users.go', './api/users/[id].go');
