name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.17.0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.3'

    - run: npm ci
    - run: npx prisma generate
    - run: npm run build
    
    - run: npm test
    